version: 2
updates:
  # Enable version updates for npm (server)
  - package-ecosystem: "npm"
    directory: "/server"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "BentleyRolling"
    assignees:
      - "BentleyRolling"
    commit-message:
      prefix: "deps(server)"
      include: "scope"
    labels:
      - "dependencies"
      - "server"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    ignore:
      # Ignore major version updates for critical dependencies
      - dependency-name: "express"
        update-types: ["version-update:semver-major"]
      - dependency-name: "axios"
        update-types: ["version-update:semver-major"]

  # Enable version updates for npm (client)
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "BentleyRolling"
    assignees:
      - "BentleyRolling"
    commit-message:
      prefix: "deps(client)"
      include: "scope"
    labels:
      - "dependencies"
      - "client"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    ignore:
      # Ignore major version updates for critical dependencies
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]
      - dependency-name: "vite"
        update-types: ["version-update:semver-major"]

  # Enable version updates for npm (root)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "BentleyRolling"
    assignees:
      - "BentleyRolling"
    commit-message:
      prefix: "deps(root)"
      include: "scope"
    labels:
      - "dependencies"
      - "root"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "BentleyRolling"
    assignees:
      - "BentleyRolling"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"