services:
  - type: web
    name: ai-search-booster
    env: node
    plan: starter
    buildCommand: npm install && cd client && npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SHOPIFY_API_KEY
        sync: false
      - key: SHOPIFY_API_SECRET
        sync: false
      - key: SHOPIFY_SCOPES
        value: read_products,write_products,read_product_listings,write_product_listings
      - key: SHOPIFY_APP_URL
        sync: false
      - key: OPENAI_API_KEY
        sync: false
