services:
  # Backend API Server
  - type: web
    name: ai-search-booster-backend
    runtime: node
    region: oregon
    plan: starter
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: SHOPIFY_API_KEY
        sync: false
      - key: SHOPIFY_API_SECRET
        sync: false
      - key: SHOPIFY_SCOPES
        value: "read_products,write_products,read_content,write_content,read_themes,write_themes"
      - key: OPENAI_API_KEY
        sync: false
      - key: APP_URL
        sync: false
    autoDeploy: true
    
  # Frontend Client
  - type: web
    name: ai-search-booster-frontend
    runtime: node
    region: oregon
    plan: starter
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/dist
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_BASE_URL
        sync: false
    autoDeploy: true

databases:
  # Optional: Add database if needed for persistent storage
  # - name: ai-search-booster-db
  #   plan: starter