# This file stores configurations for your Shopify app.

name = "ai-search-booster"
client_id = "4509cf5ef854ceac54c93cceda14987d"
application_url = "https://ai-search-booster-frontend.onrender.com"
embedded = true

[access_scopes]
scopes = "read_products,write_products,read_content,write_content,read_metafields,write_metafields"

[auth]
redirect_urls = [
  "https://ai-search-booster-backend.onrender.com/auth/callback",
  "https://ai-search-booster-frontend.onrender.com/",
  "http://localhost:3000/auth/callback",
  "http://localhost:3001/"
]

[webhooks]
api_version = "2024-01"

[[webhooks.subscriptions]]
topics = ["products/update"]
uri = "/webhooks/product_updated"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "/webhooks/app_uninstalled"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "aisearch-dev.myshopify.com"

[pos]
embedded = false