# This file stores configurations for your Shopify app.

name = "ai-search-booster"
client_id = "4509cf5ef854ceac54c93cceda14987d"
application_url = "https://ai-search-booster-frontend.onrender.com"
embedded = true

[access_scopes]
scopes = "read_products,write_products,read_content,write_content"

[auth]
redirect_urls = [
  "https://ai-search-booster-backend.onrender.com/auth/callback",
  "https://ai-search-booster-frontend.onrender.com/",
  "http://localhost:3000/auth/callback",
  "http://localhost:3001/"
]

[webhooks]
api_version = "2024-01"

[[webhooks.subscriptions]]
topics = ["products/update"]
uri = "https://ai-search-booster-backend.onrender.com/webhooks/product_updated"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "https://ai-search-booster-backend.onrender.com/webhooks/app_uninstalled"

# GDPR Compliance Webhooks (Mandatory)
[[webhooks.subscriptions]]
topics = ["customers/data_request"]
uri = "https://ai-search-booster-backend.onrender.com/webhooks/customers/data_request"

[[webhooks.subscriptions]]
topics = ["customers/redact"]
uri = "https://ai-search-booster-backend.onrender.com/webhooks/customers/redact"

[[webhooks.subscriptions]]
topics = ["shop/redact"]
uri = "https://ai-search-booster-backend.onrender.com/webhooks/shop/redact"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "aisearch-dev.myshopify.com"

[app_proxy]
url = "https://ai-search-booster-backend.onrender.com"
subpath = "ai-search-booster"
prefix = "apps"

[pos]
embedded = false