# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "ai-search-booster"
client_id = "4509cf5ef854ceac54c93cceda14987d"
application_url = "https://aisearch-dev.myshopify.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_product_listings,write_product_listings"

[auth]
redirect_urls = [
  "https://ai-search-booster.onrender.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "https://aisearch-dev.myshopify.com"
